theme: jekyll-theme-minimal
title: nhs.pycom
description: The NHS Python Community
plugins:
  - jekyll-seo-tag
google_analytics: G-XCCF9T4F20
logo: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/768px-Python-logo-notext.svg.png
