theme: jekyll-theme-minimal
title: [nhs.pycom]
description: [The NHS Python Community]
google_analytics: [G-HV4BPRJZZY]
logo: [https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/768px-Python-logo-notext.svg.png]
